name: Daily Sentiment Analysis Cron Job

on:
  schedule:
    # Run daily at 9:00 AM UTC (4 AM EST / 1 AM PST)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  sentiment-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run sentiment analysis
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
        REQUEST_TIMEOUT: 2700
      run: |
        echo "Using BASE_URL: $BASE_URL"
        cd cron
        python sentiment_fetch.py
        
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sentiment-analysis-logs-${{ github.run_number }}
        path: cron/sentiment_cron.log
        retention-days: 7
        
    - name: Log completion
      run: echo "Sentiment analysis cron job completed at $(date)"