name: Daily Sentiment Analysis Cron Job

on:
  schedule:
    # Run daily at 9:00 AM UTC (4 AM EST / 1 AM PST)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  sentiment-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd cron
        pip install -r requirements.txt
        
    - name: Run sentiment analysis
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
        REQUEST_TIMEOUT: 2700
      run: |
        cd cron
        python sentiment_fetch.py
        
    - name: Log completion
      run: echo "Sentiment analysis cron job completed at $(date)"